name: flutter_algorand_wallet
description: A new Flutter project.
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Algorand
  # algorand_dart: ^0.0.2-beta.3
  algorand_dart:
    path: ./algorand_dart

  # State Management & BLoC
  provider: ^6.0.1
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.5
  equatable: ^2.0.0

  # Fluro - Routing
  fluro: ^2.0.3

  # get_it - Service location
  get_it: ^7.2.0

  # Hive - database
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # Convert
  convert: ^3.0.0

  cupertino_icons: ^1.0.2

  feather_icons: ^1.1.0-nullsafety.0

  flutter_spinbox: ^0.6.0

  qr_flutter: ^4.0.0

  rxdart: ^0.27.2

  adaptive_dialog: ^1.2.0
  url_launcher: ^6.0.3
  clipboard: ^0.1.3
  custom_pop_up_menu: ^1.2.0
  share_plus: ^3.0.4
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing framework
  test: ^1.16.5

  # Build Runner & Source Generation
  build_runner: ^2.0.1

  # JSON serialization
  json_serializable: ^6.0.1

  # Hive generation
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/illustrations/
    # - assets/icons/
    - assets/images/
    # - assets/strings/
    # - assets/security/